"""add_roadmap_version_and_fsrs_tables

Revision ID: 8891bb15aa53
Revises: 20260511_0019
Create Date: 2026-06-06 20:23:37.103131
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8891bb15aa53'
down_revision = '20260511_0019'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_user_created'), table_name='chat_messages')
    op.drop_constraint(op.f('fk_1'), 'lessons', type_='foreignkey')
    op.create_foreign_key(None, 'lessons', 'roadmaps', ['roadmap_id'], ['id'], ondelete='SET NULL')
    op.add_column('roadmaps', sa.Column('version', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_tutor_messages_user_lesson_created'), table_name='tutor_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tutor_messages_user_lesson_created'), 'tutor_messages', ['user_id', 'lesson_id', 'created_at'], unique=False)
    op.drop_column('roadmaps', 'version')
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.create_foreign_key(op.f('fk_1'), 'lessons', 'roadmaps', ['roadmap_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_chat_messages_user_created'), 'chat_messages', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
